import Head from "next/head";
import React from "react";
import Footer from "./Footer";
import Navbar from "./Navbar";
import AddButton from "@/components/AddButton/AddButton";

export default function Layout({children}:any) {
  return (
    <>
    <Head>
    <title>le wallet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar/>
    <main>{children}</main> 
    <Footer/>
    </>
  )
}
